nautobot/nautobot-app-device-onboarding

development/nautobot_config.py
nautobot_device_onboarding/migrations/0002_create_onboardingdevice.py
nautobot_device_onboarding/models.py
nautobot_device_onboarding/nautobot_keeper.py
nautobot_device_onboarding/netdev_keeper.py
nautobot_device_onboarding/templates/nautobot_device_onboarding/onboardingtask.html
nautobot_device_onboarding/tests/test_api.py
nautobot_device_onboarding/tests/test_nautobot_keeper.py
nautobot_device_onboarding/worker.py
tasks.py

This PR ports two known issues solved in the NetBox version of the onboarding plugin. (migrations related)
Additionally, PR aligns with Nautobot 1.0.0b4 and contains fixes for :
- IP filtering (closes #9)
- Str representation of OnboardingTask object
- Fix for TYPE of interface created during onboarding
- Unit tests alignments
- Nautobot_config updates

Plugin updates (ntc-netbox-plugin-onboarding)

---

.travis.yml
development/Dockerfile
development/dev.env
development/docker-compose.yml
development/nautobot_config.py
nautobot_device_onboarding/api/serializers.py
nautobot_device_onboarding/forms.py
nautobot_device_onboarding/utils/credentials.py
nautobot_device_onboarding/worker.py
poetry.lock
pyproject.toml
tasks.py

PR implements Celery support and provides Nautobot 1.1.0 compatibility:
- Celery's availability is determined by try/except attempt during import of `nautobot.core.celery`.
- New middleware `onboard_device_worker` function per worker type (Celery, RQ)
- `Credentials` object received `nautobot_serialize` and `deserialize` methods as per Nautobot-core

Support for Nautobot 1.1.0 (Celery)

---

nautobot_device_onboarding/tests/test_onboarding.py

Extends tests to cover onboarding tasks in issues #31 & #32 
Network `netmiko`, `napalm`, `socket` are patched appropriately to test that oboarding works fine when there is indented output returned by these back-end libraries.
This PR should be re-based on deleop when CI gets fixed with another PR.
/cc @chadell

Extend unittests to cover issues #31 #32

---

README.md

Updates the doc link from devpages to the proper link.

Fix Docs Link #71

---

nautobot_device_onboarding/worker.py

Closes #117 
There was an issue with the transaction of creating an 'OnboardingTask' object not committing to the DB for the worker to access the object, thus the issue. 
The fix is to wait until the full transaction is complete to start queuing the corresponding celery worker tasks from the OnboardingTask objects.

Fix BulkAdd (Json + CSV) 

---

docs/admin/install.md
nautobot_device_onboarding/__init__.py
nautobot_device_onboarding/jobs.py
nautobot_device_onboarding/nautobot_keeper.py
nautobot_device_onboarding/tests/test_nautobot_keeper.py

Related to issue #133 , added the feature to assign the secret group used in onboarding to the device upon creation/update. Additionally added the feature to set the IP used with onboarding as managment only.

Add options to assign secret group and mgmt only interface status

---

nautobot_device_onboarding/command_mappers/cisco_ios.yml
nautobot_device_onboarding/nornir_plays/schemas.py

Found that after fixes were done for device types that only had integers I ran into the error again but it was for a serial # that only had integers. I copied what was done for the fix for device type.

Fix error if Serial # is only numbers.

---

README.md
changes/218.fixed

`:x:` and friends do not render correctly in mkdocs: 
So I've replaced all instances of emoji shortcodes with the unicode char itself.

Replace emoji shorthand to fix docs

---

README.md
changes/249.added
docs/user/app_yaml_overrides.md
nautobot_device_onboarding/command_mappers/hp_comware.yml
nautobot_device_onboarding/nornir_plays/command_getter.py
nautobot_device_onboarding/tests/mock/cisco_wlc/sync_devices/expected_result_1.json
nautobot_device_onboarding/tests/mock/hp_comware/command_getter_result_1.json
nautobot_device_onboarding/tests/mock/hp_comware/sync_devices/expected_result_1.json
nautobot_device_onboarding/tests/test_formatter.py
nautobot_device_onboarding/tests/test_transform.py

Key to getting hp_comware supportred was to support a "raw" parser, there was no other command/json/template option besides grabbing the output directly from a configuration command.  This is also going to be very valuable for other platforms where certain data fields can be more easily extracted by just running a raw command and not requiring json output.
Example
```yml
hostname:
commands:
- command: "display current | include sysname"
parser: "raw"
jpath: "raw"
post_processor: "{{ obj.lstrip().split(' ')[1] }}"
```

Add a "raw" parser concept, also add sync device platform support for hp_comware

---

changes/238.fixed
nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py

The fix added in is lines 93-98. The rest is formatting. 
Discovered when building a fresh instance from develop, using SSoT 3.1.0 and dependencies, a Pydantic error was raised when running the sync network data job on the interface field MTU. Added in an override to force a string on this field.

update to fix mtu int error

---

nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py

Add general exception handling when loading interfaces into a DiffSync model. This is used as a last resort catch for invalid data that may have slipped through schema validation or other checks.

update interface load method exception handling

---

changes/200.added
changes/255.fixed
changes/272.fixed
changes/279.fixed
nautobot_device_onboarding/jobs.py
nautobot_device_onboarding/nornir_plays/command_getter.py
nautobot_device_onboarding/nornir_plays/inventory_creator.py
nautobot_device_onboarding/nornir_plays/processor.py
nautobot_device_onboarding/tests/test_jobs.py
nautobot_device_onboarding/tests/test_sync_devices_models.py

Fixes:
- #200 
- #272 
- #279
- #255

Logging fixes, connectivity checker, sensitive data default, bogus command executions fix

---

changes/243.changed
nautobot_device_onboarding/jobs.py
nautobot_device_onboarding/templates/nautobot_device_onboarding/ssot_sync_devices.html

Closes #243 
This PR adds a Job Template form for the Sync Devices From Network job. This template uses tabs to differentiate between manual input and the csv input. The custom javascript will mark the required fields depending on the selected tab.

Mark required fields on the Sync Devices from Network job

---

changes/286.housekeeping
docs/user/app_overview.md

Fix typos on docs on the app overview file

Fix typos on docs

---

changes/277.fixed
changes/287.fixed
nautobot_device_onboarding/nornir_plays/command_getter.py
nautobot_device_onboarding/nornir_plays/transform.py

Fixes #277 
Fixes #287 
Using a `__contains` method that I still need to test using mysql.  Its working for psql as expected.

fixes out of scope logs, fix git repo provides

---

changes/293.fixed
docs/user/app_getting_started.md
docs/user/app_use_cases.md
nautobot_device_onboarding/jobs.py
nautobot_device_onboarding/nornir_plays/command_getter.py
nautobot_device_onboarding/nornir_plays/inventory_creator.py
nautobot_device_onboarding/tests/test_command_getter.py
nautobot_device_onboarding/tests/test_inventory_creator.py

This PR
* fixes code logic to make ssh public key authorization possible.
* makes small tweak to the document
* Fixes #293 
* Addresses one-bullet point of #291 - not 100% sure the best place to address the rest. Kinda seems like some of it is a core nautobot fix to expose filters to the user that are being applied when searching for a role/location/etc.
1. Made the following changes to my nautobot config:
```diff
+++ b/development/nautobot_config.py
@@ -152,6 +152,8 @@ PLUGINS_CONFIG = {
"extras": {
"fast_cli": False,
"read_timeout_override": 30,
+                    "use_keys": True,
+                    "key_file": "/source/.ssh_test/id_rsa",
},
},
},
```
2. Created an ssh rsa key at `.ssh_test/id_rsa` in this repo
2. Spun-up a containerlabs instance of an arista ceos and enabled SSH …

Fixes SSH public key auth, misc document clean-up

---

changes/306.fixed
nautobot_device_onboarding/diffsync/models/sync_network_data_models.py

Fix bug in two logging messages that cause the job to crash if hit. The log messages are only triggered when one of the attributes on the ip_address model is updated and the update fails `validated_save`.

add missing 'adapter' from logging message

---

changes/311.fixed
nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
nautobot_device_onboarding/diffsync/models/sync_network_data_models.py

- Fix bug when loading vlans
- if the untagged vlan dictionary returned from command getter is an empty dict, it should not be loaded into diffsync
- Fix bug with untagged vlan to interface assignments
- assignments are now properly removed
- Fix bug with lag to interface assignments
- assignments are now properly removed
- Fix bug with vrf to interface assignments
- assignments are now properly removed
- Add additional error handling for methods assigning objects to interfaces
- Refactor methods assigning objects to interfaces to all use the same pattern

fix loading and saving bugs with vlans, lags and vrfs

---

.github/workflows/ci.yml
changes/315.housekeeping
nautobot_device_onboarding/nornir_plays/formatter.py
nautobot_device_onboarding/tests/fakenos/custom_ios.yaml
nautobot_device_onboarding/tests/test_jobs.py
poetry.lock
pyproject.toml

* Added the [fakenos](https://github.com/fakenos/fakenos) library to spin up an SSH mock IOS device as part of unit-tests. This increases the amount of code with the ultimate goal of preventing regressions and allow further refactoring with more confidence.
* Added one log line to aid in debugging jinja errors against the job. I'll circle back and add a larger debug issue there cause I burnt a lot of time figuring out the problem.
* There is currently a bug in the CSV handling that prevents me from also adding a CSV test here. Waiting for #314 to get merged so that I can circle back and add a relevant test for that as well.
* There are two issues with fakenos atm:
1. They aren't publishing the latest code to pypi and the one that is published has its own sets of bugs that i ran into, so i …

Expand tests to cover ssh logic

---

changes/306.fixed
changes/307.dependencies
changes/311.fixed
changes/313.fixed
changes/315.housekeeping
docs/admin/release_notes/version_4.2.md
poetry.lock
pyproject.toml

- [#306](https://github.com/nautobot/nautobot-app-device-onboarding/issues/306) - Fixed error with logging message in SyncNetworkDataIPAddress.update()
- [#311](https://github.com/nautobot/nautobot-app-device-onboarding/issues/311) - Fixed issue with Lags, VRFs and Untagged Vlans not being removed from interfaces
- [#313](https://github.com/nautobot/nautobot-app-device-onboarding/issues/313) - Fixed issue running a sync job via CSV would raise an exception.
- [#307](https://github.com/nautobot/nautobot-app-device-onboarding/issues/307) - Updated ntc-templates to 7.x
- [#315](https://github.com/nautobot/nautobot-app-device-onboarding/issues/315) - Added fake SSH devices to tests to increase coverage.

Release 4.2.1

---

changes/320.fixed
nautobot_device_onboarding/constants.py
nautobot_device_onboarding/nornir_plays/command_getter.py
nautobot_device_onboarding/nornir_plays/empty_inventory.py

Nautobot core v2.4.3 upgraded to constance version 4. Constance v4 changes their database `value` field from a `PickledObjectField` to a `TextField` where they store JSON data. When we try to access constance before their `0003` data migration runs it raises a `JSONDecodeError` because the data has not yet been migrated from pickle data to JSON data. Device onboarding accesses constance at import time and prevents the database migrations from running at all.

Fixed app startup crashing nautobot during startup in some cases.

---

changes/346.fixed
nautobot_device_onboarding/jinja_filters.py
nautobot_device_onboarding/tests/test_formatter.py
nautobot_device_onboarding/tests/test_jinja_filters.py

Fixes bug where multiple IPs on a juniper interface were not being parsed. New functionality adds support for multiple IPs. 
`In [4]: item = [{'prefix_length': ['172.22.0.0/28', '172.22.0.0/28'], 'ip_address': ['172.22.0
...: .1', '127.22.0.2']}]
In [5]: parse_junos_ip_address(item)
Out[5]: 
[{'prefix_length': '28', 'ip_address': '172.22.0.1'},
{'prefix_length': '28', 'ip_address': '127.22.0.2'}]
`

added support for multiple IPs on juniper interface
